// Click-through check of the prototype flow. Run `npm run dev` (or `npm run preview`), then: npm run check
// Set URL to point somewhere else, e.g. URL=http://localhost:4173 npm run check
const { chromium } = require('playwright');
const assert = (c, m) => { if (!c) throw new Error('FAIL: ' + m); console.log('ok -', m); };
(async () => {
  const b = await chromium.launch(process.env.EX ? { executablePath: process.env.EX } : {});
  const p = await b.newPage({ viewport: { width: 1200, height: 900 } });
  const errs = []; p.on('pageerror', e => errs.push(e.message));
  await p.goto(process.env.URL || 'http://localhost:5173');
  await p.waitForTimeout(2200);
  assert(await p.isVisible('text=Choose your language'), 'splash auto-advances to language');
  await p.click('.tile[data-v="ne"]'); assert(await p.getAttribute('.tile[data-v="ne"]','aria-checked')==='true', 'Nepali tile selects');
  await p.click('text=Continue'); await p.click('text=Next'); await p.click('text=Next'); await p.click('text=Get started');
  await p.fill('#tel', '98412 345'); await p.click('text=Send code');
  assert(await p.isVisible('text=Nepali mobile numbers are 10 digits'), 'invalid number error (11)');
  assert(await p.inputValue('#tel') === '98412 345', 'typed number kept');
  await p.click('text=Terms of use'); assert(await p.isVisible('.appbar >> text=Terms of use'), 'terms opens'); await p.click('[aria-label=Back]');
  await p.fill('#tel', '9841234412'); await p.click('text=Send code');
  assert(await p.isVisible('text=+977 98•• ••• 412'), 'masked number on code screen');
  assert(await p.isDisabled('text=Verify'), 'verify disabled when empty');
  await p.keyboard.type('111111'); await p.waitForTimeout(100);
  assert(await p.isVisible("text=2 tries left"), 'auto-verify on 6th digit → wrong (08)');
  await p.click('text=Send a new code'); await p.keyboard.type('222222');
  assert(await p.isVisible("text=1 try left"), 'second wrong');
  await p.click('text=Send a new code'); await p.keyboard.type('333333');
  assert(await p.isVisible('text=Too many tries'), 'lockout (14)');
  // restart via panel to code screen
  await p.evaluate(() => jumpTo('07')); await p.fill('#code-in', '000000'); await p.waitForTimeout(100);
  assert(await p.isVisible('text=That code has expired'), 'expired (13)');
  assert(await p.isDisabled('text=Verify'), 'verify disabled on expired');
  await p.click('text=Send a new code'); await p.fill('#code-in', '123456'); await p.waitForTimeout(100);
  assert(await p.isVisible("text=Who's using the app?"), 'right code → chooser (09)');
  await p.click('text=Someone else');
  await p.click('.cta >> text=Create profile'); 
  assert(await p.isVisible('text=Choose one.') && await p.isVisible('text=Enter your date of birth.'), 'all errors at once (18)');
  await p.click('label:has-text("Female")'); assert(!(await p.isVisible('text=Choose one.')), 'choosing sex clears its error');
  await p.fill('#name', 'Anisha Sharma');
  await p.click('#dob'); await p.keyboard.type('01122050'); assert(await p.inputValue('#dob')==='01 / 12 / 2050', 'dob mask');
  await p.click('#name'); await p.waitForTimeout(100);
  assert(await p.isVisible("text=2050 is in the future in AD"), 'future date error (19)');
  await p.click('[aria-label="Choose date of birth"]'); await p.waitForTimeout(300);
  assert(await p.getAttribute('.seg[data-act="cal:BS"]','aria-pressed')==='true', 'picker opens on BS');
  assert(await p.textContent('#conv') === "That's 14 March 1994 AD.", 'BS→AD conversion: ' + await p.textContent('#conv'));
  await p.click('text=Done'); await p.waitForTimeout(100);
  assert(await p.inputValue('#dob') === '14 / 03 / 1994', 'Done fills AD date');
  assert(await p.isVisible('text=1 Chaitra 2050 BS'), 'BS shown under field (17)');
  await p.click('.cta >> text=Create profile');
  assert(await p.isVisible('text=We may already know you'), 'Sharma → possible match (22)');
  await p.click('text=Continue'); assert(await p.isVisible('text=Your records are waiting for reception'), 'waiting (23)');
  await p.evaluate(() => jumpTo('21')); await p.click('text=Send a code to'); assert(await p.isVisible('text=Enter the code'), 'session expired → code');
  // ---- Booking flow ----
  await p.evaluate(() => jumpTo('09')); await p.click('text=Anisha Sharma');
  assert(await p.isVisible('text=Your next appointment'), 'choosing yourself → Home (B01)');
  await p.click('.qa >> text=Book a visit'); assert(await p.isVisible('text=4 doctors at City Hospital'), 'Find doctor (B02)');
  await p.fill('#q', 'suman'); assert(await p.isVisible('text=1 doctor at City Hospital'), 'search filters doctors');
  await p.click('[data-act="clear-q"]'); assert(await p.isVisible('text=4 doctors at City Hospital'), 'clear search');
  await p.click('.specs >> text=Cardiology'); assert(await p.isVisible('#phone >> text=1 doctor in Cardiology') && !(await p.isVisible('[data-act="doctor:bt"]')), "Cardiology: its profile isn't designed, so the row doesn't open (SB08)");
  await p.fill('#q', 'fever'); assert(await p.isVisible('#phone >> text=Fever is usually seen in General medicine.') && !(await p.isVisible('.specs')), 'condition search explains itself (SB06)');
  await p.fill('#q', 'eye'); assert(await p.isVisible('#phone >> text=No eye doctors at City Hospital'), 'no eye doctor (SB07)');
  await p.click('[data-act="clear-q"]');
  await p.click('.specs >> text=General medicine');
  await p.click('text=Dr. Suman KC'); assert(await p.isVisible('text=No times left today'), 'no slots (B07)');
  assert(!(await p.isVisible('.cta >> text=Book')), 'no Book button when nothing to book');
  await p.click('text=See Wed, Sep 3'); assert(await p.isVisible('text=Choose a time'), 'next opening shows times');
  await p.click('[aria-label=Back]'); await p.click('text=Dr. Priya Sharma');
  assert(await p.isDisabled('.pick.day >> text=Sat'), 'Saturday closed');
  assert(await p.isDisabled('.pick.time >> text=10:30 AM'), 'taken slot disabled');
  assert(await p.isDisabled('.cta .btn'), 'Book disabled until a time is picked');
  await p.click('.pick.time >> text=4:30 PM'); await p.click('text=Book 4:30 PM today');
  assert(await p.isVisible('.appbar >> text=Review booking'), 'review (B04)');
  await p.fill('#reason', 'Fever for three days');
  await p.evaluate(() => showCases()); await p.selectOption('[data-s="failNext"]', 'taken'); await p.click('text=Confirm booking');
  assert(await p.isVisible('text=4:30 PM was just taken'), 'booking failed (B08)');
  assert(await p.inputValue('#reason') === 'Fever for three days', 'reason kept after failure');
  await p.click('text=Choose another time');
  assert(await p.isDisabled('.pick.time >> text=4:30 PM'), '4:30 now shown as taken');
  await p.click('.pick.time >> text=5:00 PM'); await p.click('text=Book 5:00 PM today'); await p.click('text=Confirm booking');
  assert(await p.isVisible('text=Appointment booked') && await p.isVisible('text=at 5:00 PM today'), 'confirmed (B05)');
  assert(!(await p.isVisible('[aria-label=Back]')), 'no back arrow on Confirmed');
  await p.click('text=Done'); assert(await p.isVisible('text=Know if Dr. Sharma is running late'), 'notifications asked after booking (B06)');
  await p.click('text=Not now'); assert(await p.isVisible('text=Today, 5:00 PM'), 'Home shows the new appointment');
  await p.evaluate(() => jumpTo('B09')); await p.click('text=Book another time');
  assert(await p.isVisible('text=No times left today'), 'cancelled → her availability without today');
  // ---- Health ----
  const pin = async digits => { for (const d of digits) await p.click(`[data-act="pin-digit:${d}"]`); await p.waitForTimeout(300); };
  await p.evaluate(() => jumpTo('B01'));
  await p.click('.bnav >> text=Health'); assert(await p.isVisible('text=Your health records are locked'), 'Health tab opens locked (H01)');
  await p.click('button.btn:text-is("Unlock")'); assert(await p.isVisible('text=Choose a PIN for your health records'), 'first unlock creates a PIN (H12)');
  await pin('1234'); assert(await p.isVisible('text=Enter it again'), 'fourth digit moves on (H13)');
  await pin('1111'); assert(await p.isVisible("text=Those PINs didn't match"), 'mismatch back to 12 with reason');
  await pin('1234'); await pin('1234'); assert(await p.isVisible('text=Use your fingerprint next time?'), 'fingerprint opt-in (H14)');
  await p.click('text=Use fingerprint'); assert(await p.isVisible('text=Taking now') && await p.isVisible('text=Your records'), 'unlocked Health (H02)');
  assert(await p.isVisible('text=1 running low'), 'Medicines row counts low stock');
  await p.click('text=Visit history'); await p.click('text=Aug 28, Dr. Priya Sharma'); assert(await p.isVisible('text=Visit on Aug 28'), 'visit detail (H04)');
  await p.click('[aria-label=Back]'); await p.click('[aria-label=Back]');
  await p.click('.list >> text=Prescriptions'); await p.click('text=Dr. Priya Sharma, Aug 28'); await p.click('text=Show to pharmacist');
  assert(await p.isVisible('text=5 days · Dispense 15 tablets'), 'show to pharmacist (H07)');
  await p.click('text=Done'); assert(await p.isVisible('.appbar >> text=Prescription'), 'Done goes back');
  await p.click('[aria-label=Back]'); await p.click('[aria-label=Back]');
  await p.click('text=Lab reports'); await p.click('text=CBC blood test'); assert(await p.isVisible('text=Your doctor is reviewing this report'), 'report being reviewed (H10)');
  await p.click('[aria-label=Back]'); await p.click('text=Thyroid panel'); assert(await p.isVisible('text=What your doctor says'), 'released report (H09)');
  // leaving the tab re-locks; fingerprint prompt, first touch fails
  await p.click('[aria-label=Back]'); await p.click('[aria-label=Back]'); await p.click('.bnav >> text=Home'); await p.click('.bnav >> text=Health');
  assert(await p.isVisible('text=Your health records are locked'), 'leaving the tab re-locks');
  await p.click('button.btn:text-is("Unlock")'); assert(await p.isVisible('text=Touch the fingerprint sensor'), 'fingerprint prompt (H15)');
  await p.click('[aria-label="Fingerprint sensor"]'); assert(await p.isVisible('text=Not recognised. Try again.'), 'not recognised (H16)');
  await p.click('text=Use PIN instead'); assert(await p.isVisible('text=Enter your PIN'), 'PIN fallback (H17)');
  for (let i = 0; i < 4; i++) await pin('0000');
  assert(await p.isVisible("text=That PIN didn't match. 1 try left."), 'wrong PIN with tries left (H18)');
  await pin('0000'); assert(await p.isVisible('text=Too many tries') && await p.isVisible('text=You can try again in 0:30'), 'too many tries (H19)');
  await p.click('text=Reset with an SMS code'); assert(await p.isVisible('text=Reset your PIN'), 'reset sheet (H20)');
  await p.click('.scrim', { position: { x: 180, y: 120 } }); assert(!(await p.isVisible('.csheet')), 'scrim = safe choice');
  await p.click('text=Reset with an SMS code'); await p.click('text=Send code');
  assert(await p.isVisible('text=Enter the code'), 'same code screen as sign-in (H21)');
  await p.fill('#code-in', '123456'); await p.waitForTimeout(200);
  assert(await p.isVisible('text=Choose a new PIN'), 'new PIN (H22)');
  await pin('5678'); await pin('5678'); assert(await p.isVisible('text=Your records'), 'confirm new PIN → straight into Health (H23)');
  // Medicines tracker
  const V = sel => p.isVisible('#phone >> ' + sel);
  await p.click('.item-title:text-is("Medicines")'); assert(await V('text=Your action is required') && await V('text=6 tablets left'), 'medicines tracker (MT01)');
  await p.click('.mt-row:has-text("Metformin")'); assert(!(await V('.mt-alert')) && await V('text=28 tablets'), 'fine stock: no warning');
  await p.click('#phone >> text=I took a dose'); assert(await V('text=Dose logged') && await V('.mt-n:text-is("27")'), 'dose logged (MT06)');
  await p.click('[aria-label=Back]'); assert(await V('text=27 tablets left'), 'back to the list, the count follows');
  await p.click('#phone >> text=Add a medicine'); await p.click('#phone >> text=Save medicine'); assert(await V("text=Enter the medicine's name."), 'manual form validates (MT02)');
  await p.fill('#mf-name', 'Omeprazole'); await p.fill('#mf-strength', '20 mg'); await p.fill('#mf-qty', '14 capsules'); await p.fill('#mf-each', '1 capsule'); await p.fill('#mf-often', 'Once a day');
  await p.click('#phone >> text=Save medicine'); assert(await V('text=Omeprazole 20 mg') && await V('text=14 capsules left'), 'manual medicine saved');
  await p.click('.mt-row:has-text("Paracetamol")'); assert(await V('text=Only 6 tablets remain'), 'low stock detail (MT05)');
  await p.click('#phone >> text=Add medicine'); assert(await p.inputValue('#mf-name') === 'Paracetamol' && await p.inputValue('#mf-qty') === '', 'restock prefilled, count empty (MT08)');
  await p.click('#phone >> text=Or tell the assistant how much you bought'); assert(await V('text=Listening…'), 'tell the assistant (MT03)');
  await p.waitForTimeout(3300); assert(await V('text=Filled in from what you said') && await p.inputValue('#mf-qty') === '20 tablets', 'review what was heard (MT04)');
  await p.click('#phone >> text=Save medicine'); assert(await V('text=26 tablets left') && !(await V('text=Your action is required')), 'restocked: the warning clears');
  await p.click('[aria-label=Back]'); await p.click('.bnav >> text=Home');
  assert(!(await V('.banner')), 'Home banner follows stock');
  // ---- Care: cancel the follow-up, so Ask can book one ----
  await p.click('.bnav >> text=Care'); assert(await p.isVisible('#phone >> text=Coming up') && await p.isVisible('#phone >> text=Past visits'), 'Care tab (C01)');
  await p.click('.card >> text=Thu, Sep 11, 10:30 AM'); assert(await p.isVisible('#phone >> text=Before you come'), 'appointment detail (C02)');
  await p.click('button:text-is("Cancel visit")'); assert(await p.isVisible('#phone >> text=Cancel your visit on Thu, Sep 11?'), 'cancel sheet (C05)');
  await p.mouse.click(180 + (await p.locator('#phone').boundingBox()).x, 120 + (await p.locator('#phone').boundingBox()).y);
  assert(!(await p.isVisible('.csheet')), 'scrim is the safe choice');
  await p.click('button:text-is("Cancel visit")'); await p.click('.csheet >> text=Cancel visit');
  assert(await p.isVisible('#phone >> text=Your Sep 11 visit is cancelled') && !(await p.isVisible('#phone >> text=Coming up')), 'cancelled, Neutral with tag (C06)');
  // ---- Ask ----
  await p.click('.bnav >> text=Ask'); assert(await p.isVisible('text=Messages is now Ask'), 'first open (A01)');
  await p.click('text=Start'); assert(await p.isVisible('text=You could ask'), 'assistant home (A02)');
  await p.click('[aria-label="Ask by voice"]'); assert(await p.isVisible('#phone >> text=Let Clinica use the microphone?'), 'first tap asks for the microphone (AM03)');
  await p.click('[data-act="mic-allow"]'); assert(await p.isVisible('text=Listening…'), 'listening (A03)');
  await p.waitForTimeout(3200); assert(await p.isVisible('text=You have one visit coming up.'), 'voice question answered (A04)');
  await p.click('.chip:has-text("Summarise my last visit")').catch(() => {});
  await p.fill('#ask-in', 'Summarise my last visit'); await p.press('#ask-in', 'Enter'); await p.waitForTimeout(800);
  assert(await p.isVisible('text=Unlock with PIN'), 'records ask for the PIN inline (A05)');
  await p.click('text=Unlock with PIN'); await pin('5678'); await p.waitForTimeout(300);
  assert(await p.isVisible('text=Dr. Priya Sharma wrote'), 'after unlocking, the answer shows (A06)');
  await p.click('button:text-is("Book follow-up")'); assert(await p.isDisabled('.cta .btn'), 'patient must choose the time (A10)');
  await p.click('.pick.time >> text=11:00 AM'); await p.click('text=Book Thu, Sep 11, 11:00 AM');
  assert(await p.isVisible("text=Your follow-up is booked. We've sent the details by SMS."), 'booked, back in the conversation (A11)');
  assert(await p.isVisible("text=A follow-up in 2 weeks isn't booked yet."), 'earlier answer unchanged');
  await p.fill('#ask-in', 'Is my thyroid result normal?'); await p.press('#ask-in', 'Enter'); await p.waitForTimeout(800);
  assert(await p.isVisible('text=Dr. Anita Joshi wrote'), 'unlock lasts for the conversation (A13)');
  await p.fill('#ask-in', 'I have chest pain'); await p.press('#ask-in', 'Enter'); await p.waitForTimeout(800);
  assert(await p.isVisible("text=If it's severe, call 102 now"), 'safety route (A12)');
  await p.click('[aria-label="New conversation"]'); assert(await p.isVisible('text=You could ask'), '+ clears the conversation');
  await p.click('.chip:has-text("Prepare for my visit")'); await p.waitForTimeout(800); await p.click('text=Add a question');
  await p.fill('#askq', 'Should I keep taking cetirizine?'); await p.click('text=Save question');
  assert(await p.isVisible('text=Should I keep taking cetirizine?') && await p.isVisible('text=Add another'), 'question saved (A19)');
  await p.fill('#ask-in', 'Summarise my last visit'); await p.press('#ask-in', 'Enter'); await p.waitForTimeout(800);
  assert(await p.isVisible('text=Unlock with PIN'), 'new conversation asks for the PIN again');
  await p.evaluate(() => showCases()); await p.check('#offline');
  await p.fill('#ask-in', 'When is my next visit?'); await p.press('#ask-in', 'Enter'); await p.waitForTimeout(800);
  assert(await p.isVisible('text=Saved at 9:12 AM'), 'offline answer (A16)');
  await p.uncheck('#offline');
  await p.click('.back-l'); assert(await p.isVisible('text=Your next appointment'), '← Home leaves for Home');
  // ---- Care: reschedule and calendar ----
  const box = await p.locator('#phone').boundingBox(), scrim = () => p.mouse.click(box.x + 180, box.y + 120);
  await p.evaluate(() => jumpTo('C02')); await p.click('#phone >> text=So you get a reminder too');
  assert(await p.isVisible('.syscal >> text=Appointment — City Hospital') && !(await p.isVisible('.syscal >> text=Priya')), 'system sheet names the clinic, not the doctor (K02)');
  assert(await p.isVisible('.syscal >> text=Thu, Sep 11, 10:30 AM') && await p.isVisible('.syscal >> text=11:00 AM'), 'sheet pre-filled with time and a 30-minute end');
  const dl = p.waitForEvent('download'); await p.click('.syscal >> text=Add'); const ics = await (await dl).path();
  const icsText = require('fs').readFileSync(ics, 'utf8');
  assert(/SUMMARY:Appointment — City Hospital/.test(icsText) && /TRIGGER:-P1D/.test(icsText) && /TRIGGER:-PT2H/.test(icsText), '.ics has the clinic title and both alerts');
  assert(await p.isVisible('#phone >> text=In your calendar'), 'saved (K03)');
  await p.click('#phone >> text=Reschedule'); assert(await p.isDisabled('.cta .btn'), 'reschedule needs a time (C03)');
  assert(await p.isDisabled('.pick.day[aria-label^="Sat"]') && await p.isDisabled('.pick.time[aria-label^="10:30 AM"]'), 'Saturday closed; the current time is not a choice');
  await p.click('.pick.day >> text=Fri'); await p.click('.pick.time >> text=11:00 AM'); await p.click('#phone >> text=Move to Fri, 11:00 AM');
  assert(await p.isVisible('#phone >> text=Visit moved') && await p.isVisible('#phone >> text=Calendar still shows Thu, Sep 11'), 'moved, calendar copy is stale (K05)');
  await p.click('[aria-label=Back]'); assert(await p.isVisible('.card >> text=Fri, Sep 12, 11:00 AM') && await p.isVisible('#phone >> text=So you get a reminder too'), 'back to the appointment, at the new time');
  await p.click('button:text-is("Cancel visit")'); await p.click('.csheet >> text=Cancel visit');
  assert(await p.isVisible('#phone >> text=Your Sep 12 visit is cancelled') && !(await p.isVisible('#phone >> text=Remove it from your calendar')), 'no calendar warning when the new time was never added');
  await p.evaluate(() => jumpTo('C02')); await p.click('#phone >> text=So you get a reminder too'); await p.click('.syscal >> text=Add');
  await p.click('button:text-is("Cancel visit")'); await p.click('.csheet >> text=Cancel visit');
  assert(await p.isVisible('#phone >> text=Remove it from your calendar'), 'cancelled after adding → remove it (K06)');
  await p.evaluate(() => jumpTo('B05')); await p.evaluate(() => showCases()); await p.check('[data-s="calOff"]');
  await p.click('#phone >> text=Add to calendar'); assert(await p.isVisible("#phone >> text=Clinica can't add to your calendar"), 'access refused (K04)');
  await scrim(); assert(!(await p.isVisible('.csheet')), 'Not now / scrim closes it'); await p.uncheck('[data-s="calOff"]');
  // ---- Care: visit day ----
  await p.evaluate(() => jumpTo('C01')); await p.click('.card >> text=Today, 4:30 PM'); assert(await p.isVisible('#phone >> text=Arrive by 4:15 PM'), 'visit day (C07)');
  await p.selectOption('[data-s="visitDay"]', 'late'); assert(await p.isVisible('#phone >> text=Dr. Sharma is running late') && await p.isVisible('#phone >> text=Reschedule instead'), 'running late (C08)');
  await p.click('#phone >> text=Reschedule instead'); assert(await p.isVisible('#phone >> text=Currently') && !(await p.isVisible('.pick.day >> text=Aug 28')), "today's visit moves within the booking week");
  await p.click('.pick.day >> text=Fri'); await p.click('.pick.time >> text=4:30 PM'); await p.click('#phone >> text=Move to Fri, 4:30 PM');
  assert(await p.isVisible('#phone >> text=Your slot today at 4:30 PM has been released'), 'today moved');
  await p.click('.btn >> text=Add to calendar'); await p.click('.syscal >> text=Add');
  await p.click('[aria-label=Back]'); assert(await p.isVisible('#phone >> text=Tomorrow, 4:30 PM') && !(await p.isVisible('#phone >> text=Reschedule instead')), 'back on the visit, booked again at the new time');
  await p.click('[aria-label=Back]'); await p.click('.bnav >> text=Home'); assert(await p.isVisible('#phone >> text=Tomorrow, 4:30 PM'), 'Home follows the move');
  await p.selectOption('[data-s="visitDay"]', 'checkedin'); await p.click('.bnav >> text=Care');
  await p.click('.card >> text=Tomorrow, 4:30 PM'); assert(await p.isVisible('#phone >> text=Waiting for Dr. Priya Sharma'), 'checked in (C09)');
  await p.selectOption('[data-s="visitDay"]', 'done'); assert(await p.isVisible('#phone >> text=Visit complete') && await p.isVisible('#phone >> text=Fri, Sep 12, 11:00 AM') === false, 'visit complete (C10)');
  await p.selectOption('[data-s="visitDay"]', 'missed'); await p.evaluate(() => jumpTo('C01')); await p.selectOption('[data-s="visitDay"]', 'missed');
  assert(await p.isVisible('#phone >> text=We missed you at 4:30 PM'), 'missed replaces the visit (C11)');
  await p.evaluate(() => jumpTo('C10')); await p.click('#phone >> text=Book follow-up'); await p.click('.pick.time >> text=10:30 AM'); await p.click('#phone >> text=Book Thu, Sep 11, 10:30 AM');
  assert(await p.isVisible('#phone >> text=Next step') && await p.isVisible('.card >> text=Thu, Sep 11, 10:30 AM'), 'follow-up booked from Care replaces the card');
  // ---- Notification centre ----
  await p.evaluate(() => jumpTo('B01')); assert(await p.isVisible('.bell .dot'), 'unread dot on the bell');
  await p.click('[aria-label^="Notifications"]'); assert(await p.isVisible('#phone >> text=Dr. Sharma is running late'), 'bell opens the centre (N01)');
  await p.click('#phone >> text=Dr. Sharma is running late'); assert(await p.isVisible('#phone >> text=No need to watch the app'), 'the delay opens in Care');
  await p.click('[aria-label=Back]'); assert(await p.locator('.nt.unread').count() === 1, 'opened row is read');
  await p.click('[aria-label="Mark all as read"]'); assert(await p.locator('.nt.unread').count() === 0, 'mark all as read');
  await p.click('[aria-label=Back]'); assert(!(await p.isVisible('.bell .dot')), 'bell dot clears');
  await p.click('[aria-label^="Notifications"]'); await p.click('#phone >> text=A lab report is ready'); assert(await p.isVisible('#phone >> text=Your health records are locked'), 'reports open through the Health lock');
  await p.evaluate(() => jumpTo('N01')); await p.click('[aria-label="Notification settings"]'); assert(await p.isVisible('#phone >> text=Appointment reminders'), 'gear opens settings (P04)');
  // ---- Profile ----
  await p.click('.bnav >> text=Home').catch(() => {}); await p.evaluate(() => jumpTo('B01')); await p.click('.bnav >> text=Profile');
  assert(await p.isVisible('#phone >> text=Patient at City Hospital') && await p.isVisible('#phone >> text=Close account'), 'Profile tab (P01)');
  await p.click('#phone >> text=Your details'); assert(await p.isVisible('#phone >> text=14 Mar 1994, or 1 Chaitra 2050 BS'), 'details in AD and BS (P02)'); await p.click('[aria-label=Back]');
  await p.click('#phone >> text=Language'); await p.click('.tile[data-v="ne"]'); await p.click('[aria-label=Back]'); assert(await p.isVisible('#phone >> text=नेपाली'), 'language follows (P03)');
  await p.click('#phone >> text=Notifications'); await p.click('[role=switch]:has-text("Follow-up reminders")');
  assert(await p.getAttribute('[role=switch]:has-text("Follow-up reminders")', 'aria-checked') === 'true', 'switch toggles at once (P04)');
  assert(await p.isDisabled('[role=switch]:has-text("Delays and cancellations")'), 'delays always on');
  await p.check('[data-s="notifOff"]'); assert(await p.isVisible('#phone >> text=Notifications are off for Clinica') && await p.isDisabled('[role=switch]:has-text("Follow-up reminders")'), 'blocked: switches disabled, value kept (P09)');
  assert(await p.getAttribute('[role=switch]:has-text("Follow-up reminders")', 'aria-checked') === 'true', 'value kept while disabled');
  await p.uncheck('[data-s="notifOff"]'); await p.click('[aria-label=Back]');
  await p.click('#phone >> text=Health lock'); await p.click('#phone >> text=Change PIN'); assert(await p.isVisible('#phone >> text=Choose a new PIN'), 'no PIN yet: straight to a new one');
  await pin('2468'); await pin('2468'); assert(await p.isVisible('#phone >> text=Locks automatically'), 'new PIN saved, back to Health lock (P05)');
  await p.click('#phone >> text=Change PIN'); assert(await p.isVisible('#phone >> text=Enter your current PIN'), 'changing asks for the current PIN (PM01)');
  await pin('2468'); assert(await p.isVisible('#phone >> text=Choose a new PIN'), 'then a new one'); await pin('1357'); await pin('1357');
  assert(await p.isVisible('#phone >> text=Locks automatically'), 'changed');
  assert(await p.isVisible('#phone >> text=PIN changed'), 'a Success note confirms it (PM04)');
  await p.click('[role=switch]:has-text("Use fingerprint")'); assert(await p.isVisible('#phone >> text=Use your fingerprint next time?'), 'turning it on goes through the opt-in (PM10)');
  await p.click('[data-act="finger:on"]'); await p.click('[aria-label=Back]'); assert(await p.isVisible('#phone >> text=PIN and fingerprint'), 'fingerprint on');
  await p.click('#phone >> text=Switch person'); await p.click('#phone >> text=Ramesh Sharma'); assert(await p.isVisible("#phone >> text=Enter Ramesh's PIN"), "Ramesh's PIN (P11)");
  await pin('0000'); assert(await p.isVisible("#phone >> text=That PIN didn't match"), 'wrong PIN');
  await pin('1961'); assert(await p.isVisible('#phone >> text=Ramesh') && await p.isVisible('#phone >> text=Your next appointment'), 'right PIN opens their Home');
  await p.click('.bnav >> text=Profile'); await p.click('#phone >> text=Sign out'); assert(await p.isVisible('#phone >> text=Sign out of Clinica?'), 'sign out sheet (P08)');
  await p.click('#phone >> text=Stay signed in'); assert(!(await p.isVisible('.csheet')), 'stay signed in');
  await p.click('#phone >> text=Close account'); assert(await p.isVisible('#phone >> text=Close your Clinica account?') && await p.isVisible('.csheet .btn.destructive'), 'close account is red (P10)');
  await p.click('.csheet >> text=Close account'); assert(await p.isVisible('#phone >> text=Your account is closed'), "says what is and isn't deleted (PM09)");
  await p.click('#phone >> text=Done'); await p.waitForTimeout(200); assert(await p.isVisible('#phone >> text=Clinica'), 'account closed → start again');
  // ---- Medicine alerts and the lock-screen push ----
  await p.evaluate(() => jumpTo('MT09')); await p.click('.push'); assert(await p.isVisible('#phone >> text=Your health records are locked'), 'push opens the medicine through the lock (MT09)');
  await p.evaluate(() => jumpTo('MT07')); assert(await p.isVisible('#phone >> text=Time for your Metformin'), 'medicine alerts (MT07)');
  await p.click('#phone >> text=Time for your Metformin'); assert(await p.isVisible('#phone >> text=Your health records are locked'), 'alerts open through the lock');
  // ---- Section 2: more states ----
  const J = async n => { await p.evaluate(n => jumpTo(n), n); await p.waitForTimeout(150); };
  const P = sel => p.isVisible('#phone >> ' + sel);
  await p.evaluate(() => showCases());
  // booking for someone else; a reply that never came
  await J('B04'); await p.click('#phone >> text=Booking for'); assert(await P('text=Who is this visit for?'), 'who is this visit for (SB01)');
  await p.click('.radio-row:has-text("Ramesh Sharma")'); assert(!(await P('.sheet')) && await P('text=Ramesh Sharma'), 'choosing closes the sheet (SB02)');
  await p.click('#phone >> text=Confirm booking'); assert(await P('text=Ramesh is booked with') && await P("text=switch to him in Profile"), 'confirmed for Ramesh (SB03)');
  await p.click('#phone >> text=Done').catch(() => {}); await p.click('[data-act="not-now"]').catch(() => {});
  assert(await P('text=Your next appointment') && await P('text=Today, 4:30 PM'), "Ramesh's visit doesn't become Anisha's");
  await J('B04'); await p.check('[data-s="offline"]'); await p.click('#phone >> text=Confirm booking');
  assert(await P("text=Couldn't send your booking"), 'offline booking (SB04)'); await p.uncheck('[data-s="offline"]');
  await p.click('.cta >> text=Try again'); assert(await P('text=Appointment booked'), 'retry is safe once online');
  await J('B04'); await p.selectOption('[data-s="failNext"]', 'noreply'); await p.click('#phone >> text=Confirm booking');
  assert(await P("text=We couldn't confirm your booking"), 'no reply (SB05)');
  await p.click('.cta >> text=Try again'); assert(await P('text=Appointment booked'), "trying again finds it already booked — no double booking");
  // filters and saved doctors
  await J('B02'); await p.click('[aria-label="Filter doctors"]'); await p.click('[data-act="fd-today"]'); await p.click('.radio-row:has-text("Female")');
  assert(await P('text=Show 1 doctor'), 'the count before applying (SB12)'); await p.click('#phone >> text=Show 1 doctor');
  assert(await P('text=Available today · Female doctor') && await P('text=Dr. Priya Sharma') && !(await P('text=Dr. Ramesh Shrestha')), 'filtered, and says so (SB13)');
  await p.click('.filt-row >> text=Clear'); assert(await P('text=4 doctors at City Hospital'), 'clear filters');
  await p.click('[data-act="doctor:ps"]'); await p.click('[aria-label="Save doctor"]'); assert(await p.getAttribute('[data-act="fav:ps"] img', 'src') === 'assets/icon-heart-filled.svg', 'saved: a filled heart (SB14)');
  await p.click('[aria-label=Back]'); assert(await P('.sec-label:text-is("Saved")'), 'saved doctors on top (SB15)');
  // reschedule: the time was taken meanwhile
  await J('C03'); await p.selectOption('[data-s="failNext"]', 'taken'); await p.click('#phone >> text=Move to Fri, 11:00 AM');
  assert(await P('text=11:00 AM on Fri was just taken') && await p.isDisabled('.pick.time[aria-label^="11:00 AM"]') && await p.isDisabled('.cta .btn'), 'time taken; current visit still booked (SC03)');
  await p.click('.pick.time >> text=3:30 PM'); await p.click('#phone >> text=Move to Fri, 3:30 PM'); assert(await P('text=Visit moved'), 'then moves');
  // visit day
  await J('C07'); for (const [v, t] of [['ontime', 'is back on time'], ['turn', 'Your turn'], ['with', 'In progress']]) {
    await p.selectOption('[data-s="visitDay"]', v); assert(await P(`text=${t}`), `visit day: ${v} (SC)`); }
  await p.selectOption('[data-s="visitDay"]', 'late'); await J('B01'); await p.selectOption('[data-s="visitDay"]', 'late'); assert(await P("text=Today's visit") && await P('text=Dr. Sharma is running late'), 'Home follows the visit day (SH02)');
  // the notification centre and the lock screen
  await J('NM02'); await p.click('#phone >> text=City Hospital cancelled your visit'); assert(await P('text=The clinic cancelled your Sep 11 visit') && await P('text=Book another time'), 'clinic cancellation: Error tone (SC06)');
  await J('N01'); await p.click('[aria-label="Mark all as read"]'); assert(!(await P('[aria-label="Mark all as read"]')), 'nothing left to mark (NM01)');
  await J('NM03'); await p.click('#phone >> text=A lab report is ready'); assert(await P('text=Unlock to see your new lab report'), 'lock screen → the report, through the lock (HM01)');
  await p.click('[data-act="unlock-start"]'); assert(await P('text=Choose a PIN for your health records'), 'first unlock creates the PIN');
  await pin('1234'); await pin('1234'); await p.click('[data-act="finger:off"]'); assert(await P('text=Dr. Sharma asked to see you'), 'lands on the report, not the hub (HM03)');
  await p.click('#phone >> text=HbA1c blood test report'); assert(await P('text=Page 1 of 1'), 'report file (HM05)');
  const dl2 = p.waitForEvent('download'); await p.click('#phone >> text=Download report'); assert((await (await dl2).suggestedFilename()).endsWith('.pdf'), 'a real PDF through the save prompt');
  // a new fingerprint on the phone
  await J('H15'); await p.check('[data-s="fingerChanged"]'); await J('H01'); await p.check('[data-s="fingerChanged"]'); await p.evaluate(() => { S.pin = '1234'; S.finger = 'on'; });
  await p.click('[data-act="unlock-start"]'); assert(await P('text=Fingerprint unlock is off') && !(await P('.bio-sheet')), 'no fingerprint prompt after a new one is added (HM07)');
  await pin('1234'); assert(await P('text=Use your fingerprint next time?'), 'then the opt-in asks again');
  // Profile: change number, add someone
  await J('P02'); await p.evaluate(() => { S.pin = '1234'; }); await p.click('#phone >> text=Mobile number');
  assert(await P('text=To change your mobile number.'), 'changing the number needs the PIN (PM05)'); await pin('1234');
  await p.fill('#tel', '9761234208'); await p.click('#phone >> text=Send code'); assert(await P('text=Sent by SMS to +977 97•• ••• 208.'), 'code to the new number (PM07)');
  await p.fill('#code-in', '123456'); await p.waitForTimeout(150); assert(await P('text=Mobile number changed') && await P('text=+977 97•• ••• 208'), 'number changed (PM08)');
  await J('P07'); await p.click('#phone >> text=Someone else'); assert(await P('text=Add someone on this phone'), 'add someone (PM11)');
  await p.click('#phone >> text=Send code'); await p.fill('#code-in', '123456'); await p.waitForTimeout(150); assert(await P("text=Who's using the app?"), 'then the record chooser');
  await J('P01'); await p.click('.item-title:text-is("Help")'); assert(await P('text=How your records are kept private'), 'Help (PM12)');
  await p.click('#phone >> text=Terms of use'); assert(await P('.appbar >> text=Terms of use'), 'Help → Terms');
  // Ask: which visit, feedback, the PIN sheet, didn't catch that
  await J('AM02'); await p.click('#phone >> text=Aug 12 · Dr. Ramesh Shrestha'); await p.waitForTimeout(800); assert(await P('text=An ear infection'), 'each option leads to its answer (AM02)');
  assert(await P('text=Was this what you needed?'), 'feedback under the answer (AM06)'); await p.click('[data-act="ask-fb:no"]');
  assert(await P('text=Sorry about that. Try asking another way'), 'not what you needed (AM07)');
  await J('AM01'); await pin('9999'); assert(await P("text=That PIN didn't match"), 'wrong PIN in the sheet');
  await pin('1234'); assert(await P('text=Dr. Priya Sharma wrote') && !(await P('.sheet')), 'the right PIN opens the answer (AM01)');
  await J('A02'); await p.evaluate(() => { S.micPerm = 'granted'; }); await p.click('[aria-label="Ask by voice"]'); await p.click('[aria-label="Stop listening"]');
  assert(await P("text=I didn't catch that."), "stopping before anything was heard (AM05)");
  await J('A02'); await p.click('[aria-label="Ask by voice"]'); await p.click('[data-act="mic-deny"]'); assert(await P('text=Voice is off. You can still type.'), 'microphone refused (AM04)');
  // across the app
  await J('B01'); await p.check('[data-s="offline"]'); assert(await P("text=You're offline. Showing what was saved at 9:12 AM.") && !(await P('.banner')), 'offline line (GX01)');
  await p.click('.bnav >> text=Care'); assert(await P("text=You're offline."), 'Care offline (GX02)'); await p.uncheck('[data-s="offline"]');
  await p.click('.bnav >> text=Care'); assert(await P('text=Updating…'), 'tapping Care again refreshes (GX05)'); await p.waitForTimeout(1400); assert(!(await P('text=Updating…')), 'refresh ends');
  await J('GX06'); await p.click('#phone >> text=Try again'); assert(await P('.sk'), 'try again → loading (GX04)'); await p.waitForTimeout(1100); assert(await P('text=Good morning,'), 'content arrives');
  // ---- Section 3: other doctors; system prompts ----
  await J('B02'); await p.click('[data-act="doctor:aj"]'); assert(await P('text=Next slot tomorrow') && await P('text=Closed on Saturdays'), 'Dr. Joshi: next slot tomorrow (OD14)');
  await p.click('.pick.day >> text=Fri'); await p.click('.pick.time >> text=9:00 AM'); await p.click('#phone >> text=Book tomorrow, 9:00 AM');
  assert(await P('text=Tomorrow, 9:00 AM'), 'review with this doctor and time (OD15)'); await p.click('#phone >> text=Confirm booking');
  assert(await P('text=booked with Dr. Anita Joshi tomorrow at 9:00 AM'), 'confirmed (OD16)');
  await p.click('#phone >> text=Done'); assert(await P('text=Good morning,') && !(await P('text=Allow notifications')), "Done goes to Home, not the notifications prompt");
  await J('P06'); await p.click('#phone >> text=Call reception'); assert(await P('.as >> text=Call +977 1-4412345'), 'the phone asks before calling (SY1)');
  assert(await p.getAttribute('.as a.as-btn', 'href') === 'tel:+97714412345', 'the confirm really dials');
  await p.click('.as-cancel'); assert(!(await P('.as')), 'cancel closes it');
  await p.click('#phone a[href="tel:102"]'); assert(await P('.as >> text=Ambulance'), 'call 102 prompt (SY2)'); await p.click('.as-cancel');
  await J('C07'); await p.click('#phone >> text=Get directions'); assert(await P('.as >> text=OPD 2, City Hospital, Maharajgunj'), 'directions prompt (SY3)'); await p.click('.as-cancel');
  await J('P09'); await p.click('#phone >> text=Open phone settings'); assert(await P(".as >> text=Open your phone's settings for Clinica?"), 'phone settings prompt (SY4)'); await p.click('.as-cancel');
  await J('K06'); await p.click('#phone >> text=Open calendar'); assert(await P('.as >> text=Open your calendar at Thu, Sep 11?'), 'open calendar prompt (SY6)'); await p.click('.as-cancel');
  await J('H09'); const dl3 = p.waitForEvent('download'); await p.click('#phone >> text=Download report'); await dl3;
  assert(await P(".as >> text=Thyroid panel report.pdf") && await P(".as >> text=Saved to your phone's Files."), 'download prompt (SY5)');
  // ---- One prototype: two ways in, and the situations in Demo inputs ----
  assert(!(await p.$('#jump')), 'no screen list in the side panel');
  await p.evaluate(() => start('empty')); assert(await P('text=Nothing booked yet') && !(await P('text=Recent')) && !(await P('.bell .dot')), 'Empty: a new patient on Home');
  await p.click('.bnav >> text=Care'); assert(await P('text=No upcoming visits'), 'Empty: Care (C12)');
  await p.click('.bnav >> text=Health'); assert(await P('text=Nothing here yet'), 'Empty: Health (H11)');
  await p.click('.bnav >> text=Ask'); assert(await P('text=Nothing to look up yet'), 'Empty: Ask (A17)');
  await p.click('.bnav >> text=Home'); await p.click('[aria-label^="Notifications"]'); assert(await P('text=No notifications yet'), 'Empty: notifications (N02)');
  await p.click('[aria-label=Back]'); await p.click('.qa >> text=Book a visit'); await p.click('[data-act="doctor:ps"]'); await p.click('.pick.time >> text=5:00 PM');
  await p.click('#phone >> text=Book 5:00 PM today'); await p.click('#phone >> text=Confirm booking'); await p.click('#phone >> text=Done');
  await p.click('[data-act="not-now"]').catch(() => {}); assert(await P('text=Today, 5:00 PM'), 'Empty: the first booking fills Home');
  await p.evaluate(() => start('full')); await p.waitForTimeout(2200); assert(await P('text=Choose your language'), 'Full: starts at the splash');
  await p.evaluate(() => jumpTo('B01')); await p.click('[data-case=edge]');
  for (const [v, t] of [['slow', 'Taking longer than usual'], ['session', 'Send a code to'], ['update', 'Update Clinica to keep going'], ['maint', 'Clinica is down for maintenance'], ['lock', 'Your 4:30 PM visit is running late'], ['push', 'Paracetamol is almost out of stock']]) {
    await p.selectOption('#open-as', v); await p.click('#open-as + button'); assert(await P(`text=${t}`), `open the app as: ${v}`); }
  await p.selectOption('#open-as', 'signedin'); await p.click('#open-as + button'); await p.waitForTimeout(1900); assert(await P('.sk'), 'signed in: splash, then Home loads (20, GX04)'); await p.waitForTimeout(1100);
  await p.selectOption('[data-s="homeState"]', 'cancelled'); assert(await P('text=Book another time'), 'doctor cancelled today (B09)');
  await p.selectOption('[data-s="homeState"]', 'walkin'); assert(await P('text=Waiting for Dr. Anita Joshi'), 'walk-in (B10)'); await p.selectOption('[data-s="homeState"]', 'default');
  await p.selectOption('#notif-set', 'meds'); await p.click('[aria-label^="Notifications"]'); assert(await P('text=Time for your Metformin'), 'medicine alerts (MT07)');
  await p.selectOption('#notif-set', 'more'); assert(await P('text=City Hospital cancelled your visit'), 'more kinds of update (NM02)');
  await p.click('.bnav >> text=Care').catch(() => {}); await p.evaluate(() => jumpTo('C02'));
  await p.check('[data-s="cancelSoon"]'); await p.click('button:text-is("Cancel visit")'); assert(await P("text=It's soon, but cancelling still helps"), 'late cancel (SC07)'); await p.click('.csheet >> text=Keep my visit');
  await p.check('[data-s="rsNone"]'); await p.click('#phone >> text=Reschedule'); assert(await P('text=No other times this week'), 'no times left (SC04)');
  await p.evaluate(() => jumpTo('C01')); await p.check('[data-s="careErr"]'); assert(await P('text=Something went wrong'), 'Care fails to load (GX07)');
  await p.click('#phone >> text=Try again'); await p.waitForTimeout(1400); assert(await P('text=Coming up'), 'try again loads Care');
  // ---- Doctor app: one world with the patient app ----
  await p.evaluate(() => start('doctor')); assert(await P("text=For City Hospital's care team"), 'doctor sign-in (D01)');
  await p.fill('#d-id', 'CH-0231'); await p.fill('#d-pw', 'nope'); await p.click('#phone >> text=Sign in');
  assert(await P('text=Staff ID or password is incorrect. Try again.'), 'wrong password (D01b)');
  await p.fill('#d-pw', 'clinica'); await p.click('#phone >> text=Sign in');
  assert(await P('text=5 of 8 seen today') && await P("text=You're with Nabin Tamang now. Anisha Sharma is next."), "today's queue (D02)");
  await p.evaluate(() => switchPhone()); assert(await P("text=You're checked in"), "switching phones: Anisha's Home shows her checked in");
  await p.evaluate(() => switchPhone()); assert(await P('text=5 of 8 seen today'), 'and back to the queue, where it was');
  await p.click('[data-act="d-patient:sk"]'); assert(await P('text=Not arrived') && !(await P('text=Start visit')), 'not arrived: no Start visit (D03e)'); await p.click('[aria-label=Back]');
  await p.click('[data-act="d-patient:bt"]'); assert(await P('.tag >> text=Visit complete'), 'done (D03d)'); await p.click('[aria-label=Back]');
  await p.click('[data-act="d-patient:as"]'); await p.click('#phone >> text=View history'); assert(await P('text=Dr. Ramesh Shrestha · Ear infection'), 'visit history (D03b)'); await p.click('[aria-label=Back]');
  await p.click('#phone >> text=Start visit'); assert(await P("text=Doctor's note") && await P('text=For fever and headache'), 'complete visit (D04)');
  await p.fill('#d-note', 'A viral infection. Rest and fluids. Come back if the fever lasts more than 3 days.'); await p.click('.radio-row:has-text("No follow-up")');
  await p.click('.btn:text-is("Complete visit")'); assert(await P('text=7 of 8 seen today') && await P('.dq-t:has-text("Anisha Sharma") >> text=Done') && await P('.dq-t:has-text("Nabin Tamang") >> text=Done'), 'Anisha done; Nabin done too');
  await p.evaluate(() => switchPhone()); await p.evaluate(() => { S.screen = 'cday'; S.stack = ['care']; render(); });
  assert(await P('text=Visit complete') && await P('text=No follow-up needed'), "Anisha's Care follows the doctor: visit complete, no follow-up");
  await p.evaluate(() => { S.unlocked = true; S.visit = 'aug28'; S.screen = 'hvisit'; render(); });
  assert(await P('text=Rest and fluids.'), "the note she reads is the one the doctor wrote");
  await p.evaluate(() => switchPhone()); await p.click('.bnav >> text=Reports'); assert(await P('text=2 results are waiting on you'), 'reports (D05)');
  await p.click('[data-act="d-report:cbc"]'); assert(await P('text=13.2 g/dL') && await P('text=Release to Anisha'), 'report detail (D06)');
  await p.click('.radio-row:has-text("I need to see them again")'); assert(await P('text=Release with follow-up request') && await p.inputValue('#d-comment') === 'Please book a follow-up so we can discuss this.', 'flag follow-up (D06b)');
  await p.click('#phone >> text=Release with follow-up request'); assert(await P('text=1 result is waiting on you') && !(await P('text=CBC blood test')), 'released, off the list');
  await p.click('[data-act="d-report:lipid"]'); await p.click('#phone >> text=Release to Kabita'); assert(await P('text=Nothing waiting on you'), 'no reports pending (D05b)');
  await p.evaluate(() => switchPhone()); await p.evaluate(() => { S.screen = 'home'; S.stack = []; render(); }); await p.click('[aria-label^="Notifications"]');
  await p.click('#phone >> text=A lab report is ready'); await p.evaluate(() => { S.unlocked = true; S.screen = 'hreport'; S.stack = ['health', 'hlabs']; render(); });
  assert(await P('text=CBC blood test') && await P('text=Dr. Sharma asked to see you') && await P('text=Please book a follow-up so we can discuss this.'), "Anisha sees the released CBC, with the doctor's comment and the asked-to-see-you card");
  await p.evaluate(() => switchPhone()); await p.click('.bnav >> text=Profile'); assert(await P('text=NMC registration'), 'doctor profile (D07)');
  await p.click('#phone >> text=Notifications'); assert(await P('[role=switch]:has-text("Schedule changes")[aria-checked="false"]'), 'account settings (D07b)');
  await p.click('[role=switch]:has-text("Schedule changes")'); assert(await P('[role=switch]:has-text("Schedule changes")[aria-checked="true"]'), 'switch toggles');
  await p.fill('#d-pw1', 'short'); await p.click('#phone >> text=Save password'); assert(await P('text=Use at least 8 characters.'), 'password rules');
  await p.click('[aria-label=Back]'); await p.click('#phone >> text=Sign out'); assert(await P("text=For City Hospital's care team"), 'sign out');
  // ---- Doctor desktop: same day, third device ----
  await p.evaluate(() => start('desk')); assert(await p.evaluate(() => document.getElementById('phone').classList.contains('desk')), 'desktop stage (1440 × 900)');
  await p.fill('#d-id', 'CH-0231'); await p.fill('#d-pw', 'x'); await p.click('#phone >> text=Sign in'); assert(await P('text=Staff ID or password is incorrect'), 'desktop wrong password');
  await p.fill('#d-pw', 'clinica'); await p.click('#phone >> text=Sign in'); assert(await P('text=Select a patient') && await P('text=Aug 28 · 5 of 8 seen'), 'nothing pre-selected (K10)');
  await p.click('[data-act="k-sel:sk"]'); assert(await P('text=Scheduled visit') && await P('.k-hd >> text=Not arrived'), 'not arrived (K11e)');
  await p.click('[data-act="k-sel:bt"]'); assert(await P("text=Today's visit — complete"), 'visit complete (K11d)');
  await p.click('[data-act="k-sel:nt"]'); await p.click('#phone >> text=View history'); assert(await P('text=Dr. Priya Sharma · Follow-up'), "Nabin's own history (K12g)");
  await p.click('#phone >> text=Back to visit'); await p.click('[data-act="k-sel:as"]'); assert(await P('text=Start visit'), 'Anisha (K11)');
  await p.click('#phone >> text=Start visit'); assert(await P("text=Doctor's note") && await P('.k-row.sel >> text=With you now'), 'completing inline (K11b)');
  await p.click('.radio-row:has-text("In 2 weeks")'); await p.click('.k-hd >> text=Complete visit');
  assert(await P("text=Today's visit — complete") && await P('text=Aug 28 · 7 of 8 seen'), 'completed: read-only, the count moves');
  await p.click('.k-ni >> text=Reports'); assert(await P('text=Select a report') && await P('text=2 are waiting on you'), 'reports, nothing selected (K20a)');
  await p.click('[data-act="k-rep:cbc"]'); await p.click('.radio-row:has-text("I need to see them again")'); assert(await P('text=Release with follow-up request'), 'flag follow-up (K20b)');
  await p.click('#phone >> text=Release with follow-up request'); assert(await P('text=1 is waiting on you'), 'released');
  await p.evaluate(() => showApp('doctor')); assert(await P('text=1 result is waiting on you') || await P('text=7 of 8 seen today'), "the doctor's phone shows the same day");
  await p.evaluate(() => showApp('patient')); await p.evaluate(() => { S.screen = 'cday'; S.stack = ['care']; render(); });
  assert(await P('text=Visit complete') && await P('text=Follow-up in 2 weeks'), "Anisha's phone: visit complete, follow-up in 2 weeks advised");
  await p.evaluate(() => showApp('desk')); await p.click('.k-ni >> text=Profile'); assert(await P('text=NMC registration'), 'desktop profile (K30)');
  await p.click('#phone >> text=Change password'); assert(await P('text=Save password') && await P('text=Schedule changes'), 'account settings (K30b)');
  await p.click('.k-ni >> text=Profile'); await p.click('#phone >> text=Sign out'); assert(await P('.k-card'), 'desktop sign out → the card');
  // ---- Hospital staff web app: admin, front desk and HR, same day ----
  const signStaff = async (id, pw = 'clinica') => { await p.fill('#st-id', id); await p.fill('#st-pw', pw); await p.click('#phone >> text=Sign in'); };
  await p.evaluate(() => start('staff')); assert(await P('text=Hospital management — City Hospital'), 'staff sign-in (T00)');
  await signStaff('CH-ADM-04', 'nope'); assert(await P('text=Admin ID or password is incorrect. Try again.'), 'wrong password (T00b)');
  await signStaff('CH-ADM-04'); assert(await P('.st-stat:has-text("Reports pending") >> text=7') && await P('.st-stat:has-text("Not yet arrived") >> text=2'), 'admin dashboard counts from the shared day (T01)');
  await p.click('#phone >> text=View all doctors'); assert(await P('text=8 on the roster · 6 on duty today'), 'doctors roster (T02)');
  await p.click('[data-act="st-menu:dept"]'); await p.click('[data-act="st-f:dept|Dermatology"]'); assert(await P('text=2 of 8 · filtered by department'), 'department filter (T02d)');
  await p.click('.st-ttl'); assert(!(await P('.st-dd')), 'a click outside closes the panel');
  await p.click('[data-act="st-f:dept|Dermatology"]').catch(() => {}); await p.click('.k-ni >> text=Departments'); await p.click('[data-act="st-dept:derm"]');
  assert(await P('text=Staff on leave') && await P('text=Dr. Maya Shrestha · OPD 5'), 'department detail (T03b)');
  await p.click('.k-ni >> text=Patients'); await p.click('[data-act="st-pat:as"]'); assert(await P('text=Dr. Ramesh Shrestha · Ear infection') && await P('text=Female · 32 · CH-2381'), "Anisha's record matches her apps (T05a)");
  await p.click('#phone >> a.k-link'); await p.click('[data-act="st-menu:date"]'); await p.click('[data-act="st-day:20"]'); await p.click('[data-act="st-day:28"]');
  assert(await P('text=12 of 15 · filtered by last visit'), 'date range filters by last visit (T05c)');
  await p.click('.k-ni >> text=Settings'); await p.click('#phone >> text=Add a doctor'); await p.click('#phone >> text=Add doctor'); assert(await P("text=Enter the doctor's full name."), 'add doctor needs a name');
  await p.fill('#sa-name', 'Kabita Shrestha'); await p.fill('#sa-spec', 'Cardiology'); await p.click('#phone >> text=Add doctor');
  assert(await P('text=Dr. Kabita Shrestha has been added'), 'doctor added (T04a2)'); await p.click('#phone >> text=View in roster');
  assert(await P('text=9 on the roster') && await P('text=Dr. Kabita Shrestha'), 'the new doctor is on the roster');
  await p.click('.k-ni >> text=Settings'); await p.click('#phone >> text=Assign roles'); await p.click('[aria-label="Select Sabina Rai"]'); await p.click('[aria-label="Select Rajesh Koirala"]');
  assert(await P('text=2 selected'), 'bulk selection (T04b2)'); await p.click('[aria-label="Select Rajesh Koirala"]');
  await p.click('#phone >> text=Assign role to selected'); assert(await P('text=What Front desk can access'), 'role picker (T04c)');
  await p.click('[data-act="st-pick:hr"]'); assert(await P('text=Leave requests and approvals'), 'access follows the chosen role');
  await p.click('[data-act="st-pick:desk"]'); await p.click('#phone >> text=Save role'); assert(await P('text=Sabina Rai is now Front desk.'), 'role saved');
  await p.click('.k-me'); await p.click('.st-dd >> text=Sign out'); assert(await P('.k-card'), 'staff sign out');
  // Front desk
  await signStaff('CH-FD-12'); assert(await P('text=13 patients across the hospital') && await P('.k-row:has-text("Nabin Tamang") >> text=With doctor'), "front desk: today's arrivals follow the doctor's queue (R01)");
  await p.fill('#st-q', 'sunita'); assert(await P('text=1 result for “sunita”'), 'search (R01c)');
  await p.click('[data-act="st-arr:sk"]'); await p.click('#phone >> text=Check in'); assert(await P('text=Checked in at 4:52 PM'), 'checked in (R03)');
  assert(await p.evaluate(() => drStatus('sk')) === 'waiting', "Sunita is now Waiting in Dr. Sharma's queue");
  await p.click('#phone >> a.k-link'); await p.click('#phone >> text=Register a walk-in'); await p.fill('#wk-name', 'Sunita'); await p.fill('#wk-doc', 'Dr. Suman KC');
  await p.click('#phone >> text=Add to queue'); assert(await P("text=Dr. Suman KC isn't in today"), "can't add a walk-in for a doctor who's off");
  await p.fill('#wk-doc', 'priya'); await p.fill('#wk-reason', 'Sore throat'); await p.click('#phone >> text=Add to queue');
  assert(await P('text=Is this Sunita?') && await P('text=phone ending 8821'), 'name matches two records (R06)');
  await p.click('#phone >> text=None of these — register as new patient'); assert(await P('text=14 patients across the hospital'), 'walk-in added to arrivals');
  assert(await p.evaluate(() => drToday().some(k => DR_PATIENTS[k].name === 'Sunita' && drStatus(k) === 'waiting')), "and to Dr. Sharma's own queue");
  await p.click('#phone >> text=Register a walk-in'); await p.click('.radio-row:has-text("Follow-up visit")'); await p.fill('#wk-name', 'Kiran Basnet');
  assert(await P('text=Dr. Ramesh Shrestha · Chest infection'), 'follow-up shows recent visits (R05)');
  await p.click('.k-me'); await p.click('.st-dd >> text=Sign out');
  // HR
  await signStaff('CH-HR-03'); assert(await P('text=15 people · 1 on leave'), 'HR staff directory, with the new doctor (HR01)');
  await p.click('[data-act="st-menu:role"]'); await p.click('[data-act="st-f:role|Nurse"]'); assert(await P('text=2 of 15 · filtered by role'), 'role filter (HR01b)');
  await p.click('[data-act="st-person:mt"]'); assert(await P('text=CH-STF-0231'), 'staff record (HR02)');
  await p.click('.k-ni >> text=Leave requests'); assert(await P('text=1 pending · 1 already approved'), 'leave requests (HR03)');
  await p.click('[data-act="st-req:pk"]'); await p.click('#phone >> text=Approve'); assert(await P('text=Approved — Prasant has been notified'), 'approved (HR05)');
  await p.click('#phone >> a.k-link'); assert(await P('text=No pending requests') && await P('text=History'), 'none pending, history kept (HR03b)');
  await p.click('.k-ni >> text=Attendance'); await p.click('[data-act="st-menu:absent"]'); await p.click('[data-act="st-sort:absent-desc"]');
  assert(await p.textContent('.st-rows .st-tr .nm') === 'SKDr. Suman KC', 'sorted by absences (HR08b)');
  await p.click('[data-act="st-att:ms"]'); assert(await P("text=Leave continues through Sep 2 — shown on next month's attendance."), "Maya's attendance (HR09)");
  console.log('page errors:', errs);
  await b.close();
})().catch(e => { console.error(e.message); process.exit(1); });
